from src.pre_computation import write_movies_info_file, COLUMNS_MOVIES_PLOT_GENRE
from src.similarities_util import PATH_TO_TOP_100_JSON, PATH_TO_DESCRIPTION_TOP_100

write_movies_info_file(PATH_TO_TOP_100_JSON, PATH_TO_DESCRIPTION_TOP_100, COLUMNS_MOVIES_PLOT_GENRE)
